## Colors configuration
[colors.primary]
background = "#121212"
foreground = "#e0e0e0"

[colors.normal]
black   = "#121212"
red     = "#3a3a3a"
green   = "#5f5f5f"
yellow  = "#767676"
blue    = "#8c8c8c"
magenta = "#a8a8a8"
cyan    = "#c6c6c6"
white   = "#e0e0e0"

[colors.bright]
black   = "#303030"
red     = "#4e4e4e"
green   = "#6c6c6c"
yellow  = "#878787"
blue    = "#9e9e9e"
magenta = "#bcbcbc"
cyan    = "#d7d7d7"
white   = "#f5f5f5"
